icons_format = "{icon}"

[theme]
# theme = "bad-wolf"
theme = "srcery"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "net"

[[block]]
block = "memory"
format = " $icon $mem_used.eng "

[[block]]
block = "load"
format = " $icon  $1m.eng(w:4) $5m.eng(w:4) $15m.eng(w:4) "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon  $available.eng(w:2) "

[[block]]
block = "backlight"
invert_icons = true

[[block]]
block = "battery"
format = " $icon $percentage {$time |}"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

